/** Cestas reais da plataforma usadas nas lojas de exemplo (uso autorizado). Chave = nome curto; valor = slug do produto. */
export const S = {
  premium: "nova-cesta-muipr2pw",
  pink: "nova-cesta-criancas-muimg6te",
  flores: "nova-cesta-arranjo-flores-mu3e1iz1",
  lady: "nova-cesta-muipeoip",
  memoravel: "cesta-memoravel",
  frios: "nova-cesta-mtwbo29q",
  confraria: "nova-caixa-presente-muhozgsi",
  sinha: "nova-cesta-maes-muhqb46z",
  maestro: "nova-caixa-pai-homem-muhokijx",
  amor: "nova-cesta-namorados-muhsajcb",
  aconchego: "cesta-aconchego",
  essencia: "cesta-essencia",
  executivo: "nova-cesta-executivo-muiluxwv",
  encanto: "cesta-encanto",
  blue: "nova-cesta-dia-das-criancas-muimcd7r",
  porDoSol: "nova-cesta-tarde-muimktaf",
  afeto: "cesta-afeto",
  orquidea: "nova-cesta-mu3dwun6",
  baloes: "nova-cesta-mu3e8s1h",
  kolanchoe: "nova-cesta-mu3dyz8m",
  ferrero: "nova-cesta-mu3ec8zz",
  miniBolo: "nova-cesta-mu3dubq8",
  coracao: "nova-cesta-mu3e4x6m",
  caneca: "nova-cesta-mu3dbd2p",
};
